image: node:latest

stages:
    - client-build
    - server-build

Client Build:
    stage: client-build
    script:
        - cd "client"
        - npm install
    artifacts:
        paths:
            - /home/gitlab-runner/client/

Server Build:
    stage: server-build
    script:
        - cd "server"
        - npm install
    artifacts:
        paths:
            - /home/gitlab-runner/server/
