image: node:latest

stages:
    - client-build
    - server-build
    - test

Client Build:
    stage: client-build
    script:
        - cd "client"
        - npm install

Server Build:
    stage: server-build
    script:
        - cd "server"
        - npm install

Test:
    stage: test
    script:
        - cd "client"
        - npm test
