image: docker/compose:latest

services:
    - docker:dind

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""

stages:
    - setup-mongo
    - client-build
    - server-build
    - test-client
    - test-server

#before_script:
#    - apk update && apk add curl
#    - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
#    - chmod +x /usr/bin/docker-compose
#    - /usr/bin/docker-compose --version

Setup MongoDB:
    stage: setup-mongo
    script:
        - cd "mongo"
        - docker-compose config
        - docker-compose up -d
    tags:
        - docker
    #artifacts:
     #   paths:
      #  - mongo/data/db

Client Build:
    stage: client-build
    script:
        - cd "client"
        - npm install

Server Build:
    stage: server-build
    script:
        - cd "server"
        - npm install

Test Client:
    stage: test-client
    script:
        - cd "client"
        - npm install
        - npm test
    dependencies:
        - Client Build

Test Server:
    stage: test-server
    script:
        - cd "server"
        - npm install
        - npm test
    dependencies:
        - Server Build
        - Setup MongoDB
    tags:
        - docker
    variables:
        MONGO_URI: "mongodb://mongo:27017/UnoProgetto"