image: node:latest

stages:
    - client-build
    - server-build
    - test

Client Build:
    stage: client-build
    script:
        - cd "client"
        - npm install

Server Build:
    stage: server-build
    script:
        - cd "server"
        - npm install

Test Client:
    stage: test-client
    script:
        - cd "client"
        - npm install
        - npm test
    dependencies:
        - Client Build

Test Server:
    stage: test-server
    script:
        - cd "server"
        - npm install
        - npm test
    dependencies:
        - Server Build